### ISSUE TITLE
drag and drop from Outlook 2010 64-bit error

### ISSUE THREAD

**Issue by JeanDUPOND** [landrix/The-Drag-and-Drop-Component-Suite-for-Delphi#12]
Hi Sven,

I have a problem with your component in Delphi XE7 compiling 64-bit.

I try to do a drag and drop from Outlook 2010 64-bit, but I encounter an error in the function LoadMAPI32 on :
GetProc('MAPIGetDefaultMalloc@0', pointer( @MAPIGetDefaultMalloc));

The error is :
"MAPI initialization failed: Failed to get mapi32.dll entry point for MAPIGetDefaultMalloc@0: The specified procedure could not be found. Drag and drop and paste will not be functional."

Outlook and my application are both administrator rights.

I made any kind of test, but now I do not know what to try.

Do you have an idea ?

**Comment by landrix** [comment]
it seames the 64 bit support isn't implementet

https://github.com/DelphiPraxis/The-Drag-and-Drop-Component-Suite-for-Delphi/search?utf8=%E2%9C%93&q=LoadMAPI32+

if i have time, i can take a look on this.

**Comment by JeanDUPOND** [comment]
OK, thanks. 
      I also look to my side to see what it is possible to do.
      Sven Harazim a écrit :
    
    if i have time, i can take a look on this.

**Comment by landrix** [comment]
ca you try the current rev 

https://github.com/DelphiPraxis/The-Drag-and-Drop-Component-Suite-for-Delphi/commit/9f0193de17020d8811c3474c7a80ef454c492e75

i don't have Outlook

**Comment by JeanDUPOND** [comment]
Hello Sven,
      
      No, I still have the message:
      ---------------------------
      Outlook Drop Target demo
      ---------------------------
      Failed to get mapi32.dll entry point for MAPIGetDefaultMalloc@0:
      The specified procedure could not be found.
      ---------------------------
      
      I am running on Windows 10 with a 64-bit compilation in Delphi
      XE7.
      
      Best regards
      Sven Harazim a écrit :
    
    
      ca you try the current rev 
      9f0193d
      i don't have Outlook
      —
        You are receiving this because you authored the thread.
        Reply to this email directly or view
          it on GitHub

**Comment by JeanDUPOND** [comment]
Hello Sven,
      
      you can take a look on :
      
https://msdn.microsoft.com/en-us/library/office/cc963763.aspx#sectionSection2
      
      https://mapistublibrary.codeplex.com/
      
      Best regards
      Sven Harazim a écrit :
    
    
      ca you try the current rev 
      9f0193d
      i don't have Outlook
      —
        You are receiving this because you authored the thread.
        Reply to this email directly or view

          it on GitHub

**Comment by landrix** [comment]
hav you tried the x64 target from 

https://github.com/DelphiPraxis/The-Drag-and-Drop-Component-Suite-for-Delphi/tree/master/DemosWithoutInstall/Outlook

?

**Comment by dr-consit** [comment]
@JeanDUPOND I know this is an old issue, but if you ever want to revisit this, I believe the patch from: #34 / 4f3a6e941eb4364c241b13728a74e7b1a034b061 fixes this issue.

**Comment by landrix** [comment]
ok, then i will close this here, thanks
