### ISSUE TITLE
.Zip Files can't be dropped

### ISSUE THREAD

**Issue by Magiermacht** [landrix/The-Drag-and-Drop-Component-Suite-for-Delphi#15]
Hi. 

I don't know if this is a known issue, but it wasn't among the closed ones. 
I made a simple Prototype Programm with this component but i can't drop .zip files. 

It works if i just change the File-Extention but as soon as Windows recognises it as a .Zip file the Drop won't work. 

I made a Stack-Overflow entry some time ago with some Informations i've gathered: 
http://stackoverflow.com/questions/32653773 

(I've already tried it with this Version) 
I Hope you can help me. 

Kind regards
Magiermacht

**Comment by landrix** [comment]
Which source of D&D do you use? On SO you wrote about http://melander.dk/delphi/dragdrop

**Comment by Magiermacht** [comment]
I've tried it with the original Version but also with the one in this git Repository (and some other Repository i've found but it seemed left behind)
