### ISSUE TITLE
Explorer Shell Extension with Icon don't get Selected in W7 64

### ISSUE THREAD

**Issue by antekgla** [landrix/The-Drag-and-Drop-Component-Suite-for-Delphi#25]
Hi, I made a Explorer Shell Extension based in **ShellContextMenuHandlerSimple** and works fine.
My problems start when I add a Icon (or BMP) to my Item Menu.
When an image is added the Menu still works as intended but dont change his background when is selected.
I try with a ImageList attached to PopUpMenu and ImageIndex for my ItemMenu and this is the result:

![context2](https://user-images.githubusercontent.com/24402722/30869183-e3fc6d88-a2b6-11e7-8e71-2118435c0578.gif)

When I made the same but with a Bitmap assigned directly to my ItemMenu the result is slightly better. Can I see a bit of the background changing at left (back of the image). Like this:

![context1](https://user-images.githubusercontent.com/24402722/30869299-27bcaa92-a2b7-11e7-86f1-b1d40a974b88.gif)

**It is as if the Menu Text were in a upper layer and cover the background.**

_Remarks:_

I compile the **ShellContextMenuHandlerSimple** original without any changes and same result. The items with Bitmaps dont get his background changed.

I compile my Shell Extensions for 32 bit and tested in WinXP and works OK. (programatically and visually).

Any ideas?
Thanks in advance!

PD: My system W7 64 bits. Delphi XE2.

**Edit**: i just realized that the include of a bitmap in the Shell Extension Menu **change drastically** the visual of the all right click menu (at least the background part). Compare my Right Click menu with my extension **without any bitmap** (this is W7 regular behaviour)  with the Shell Extension with bitmap.

![context3](https://user-images.githubusercontent.com/24402722/30889428-b5d6c0ca-a2fc-11e7-9b77-6f5f7c7e325a.gif)![context1](https://user-images.githubusercontent.com/24402722/30869299-27bcaa92-a2b7-11e7-86f1-b1d40a974b88.gif)

**Comment by emartisoft** [comment]
Hi,
I have the same problem. My solution is in the following lines. Firstly, Open ShellContextMenuHandlerSimple project in the demos folder.

`PopupMenu1.OwnerDraw:=true;`

Click events tab for test1 (Menuitem) in Object Inspector. Create OnDrawItem event.

>procedure TDataModuleContextMenuHandler.test1DrawItem(Sender: TObject;
>  ACanvas: TCanvas; ARect: TRect; Selected: Boolean);
>var
> s: string;
>begin
 > s := (Sender as TMenuItem).Caption;
>  s := s + StringOfChar(' ', 255 - Length(s));
 > ACanvas.TextOut(ARect.Left + 32, ARect.Top + 2 , s);
 > ACanvas.Draw(10,0, test1.Bitmap);
>end;

PS: Do not change menuitem's bitmap properties to NULL (do not clear bitmap). It does not works.

Compile and install via regsvr32.exe

Screenshot link
http://i68.tinypic.com/157dkrn.jpg

**Comment by ruslancnua** [comment]
Just comment code in Source\DragDropContext.pas
procedure procedure TDropContextMenu.DrawMenuItem(var DrawItemStruct: TDrawItemStruct);
line 
       if (odSelected in State) then
        begin
          Canvas.Brush.Color := clHighlight;
          Canvas.Font.Color := clHighlightText;
          Exclude(State, odSelected); - this is problem, comment this

        end else

**Comment by landrix** [comment]
i commented out this, please check again
