### ISSUE TITLE
Outlook demo missing critical statement

### ISSUE THREAD

**Issue by david-navigator** [landrix/The-Drag-and-Drop-Component-Suite-for-Delphi#27]
The demo The-Drag-and-Drop-Component-Suite-for-Delphi-master\DemosWithoutInstall\Outlook

doesn't work.

As far as I can see it requires the line

`  
DataFormatAdapterOutlook.enabled := true;
`
adding to the end of 
procedure TFormOutlookTarget.FormCreate(Sender: TObject);
in OutlookTarget.pas

That said, I still can't get the demo to grab data from Outlook, but it get's significantly further now.

**Comment by david-navigator** [comment]
Tried this demo now with several different versions of Outlook, it definitely doesn't work compiled under D XE10.1 (Berlin SP2).
Oddly seems to lockup on 
`      if (Supports(OutlookDataFormat.Messages[i], IMessage, AMessage)) then `
not sure how though.

Anyone else got this working ?

**Comment by david-navigator** [comment]
Just realised, if my Delphi app is compiled as 32 bit and Outlook is 64 bit, I'm guessing that the two won't talk to each other ?

**Comment by worms618** [comment]
I compiled my Delphi app as a 64 and have Outlook installed as 64 bit. Everything looks to be working for me again.

**Comment by landrix** [comment]
https://github.com/landrix/The-Drag-and-Drop-Component-Suite-for-Delphi/issues/38

**Comment by landrix** [comment]
not possible, sry, only 32<>32 and 64 <>64
