### ISSUE TITLE
Problem with D&D in W7P 64b (VMware)

### ISSUE THREAD

**Issue by theOndrap** [landrix/The-Drag-and-Drop-Component-Suite-for-Delphi#33]
Hello, I'm quite sure thats not a Component issue, because it works fine for me under w10 (non VMware). 
But with this configuration (see title) I'm not able to perform drag&drop. I'm using your demo 'SimpleTarget' (but its general behavior) and when I drag file (from explorer) then I can't drop them to the form just because its disabled ... Icon disabled as well (you know, the crossed circle). I spend half day but I can't find the solution. 
Note: The SimpleTargetDemo is not using elevated privileges.

thanks in advice, Ondrej

**Comment by landrix** [comment]
do you have it checked with current sources?

**Comment by landrix** [comment]
ok, reopen this issue, if it still exists.
