### ISSUE TITLE
How get Source directory with Delphi? 

### ISSUE THREAD

**Issue by alefsoft1** [landrix/The-Drag-and-Drop-Component-Suite-for-Delphi#35]
How to get the source path with this component suite? For example: I dropped file (virtual file) from my app to the desktop. I only need then source path i.e: Desktop. How to get this path before call DropFileSource1.Execute?
Here is my code on ListView1MouseDown procedure:
  ipwFTP1.LocalFile :=source path+'salam.txt';

**Comment by landrix** [comment]
i think, it is not possible to detect, what the target application do with your dragged object.

https://stackoverflow.com/questions/16941088/how-to-detect-target-when-i-drag-from-qt-application-and-drop-to-windows-explore
