### ISSUE TITLE
Drag and drop between two delphi executables

### ISSUE THREAD

**Issue by gitjcr** [landrix/The-Drag-and-Drop-Component-Suite-for-Delphi#36]
Hi.

Specifically I want to copy/move a structure like the following:

treenode+blobfield (in some cases it could be more than one set of treenode+blobfield)

I've been watching the demos but I'm not clear.

Can someone tell me?. A small explanation, an example of code, demos/sources to use, etc

Thanks in advance

**Comment by landrix** [comment]
i think Demos/CustomFormat1 can help you
