### ISSUE TITLE
tDropFileSource from delphi 32bit application to outlook 64bit

### ISSUE THREAD

**Issue by MicrotronX** [landrix/The-Drag-and-Drop-Component-Suite-for-Delphi#38]
Hi, if i use tDropFileSource with

mytDropFileSource.files.add(vpathtoafile);
mytDropFileSource.Execute;

i can drop files to desktop but not to Outlook 64bit. Is this a known limitation somehow with 32bit and 64bit apps or is it a bug?

**Comment by MicrotronX** [comment]
Can be tested with SimpleSourceDemo, Drag&Drop a File to a new E-Mail from Outlook-2019 in 64bit and it will not dropped into the new e-mail ...

**Comment by landrix** [comment]
It seems to be a outlook bug.

https://social.msdn.microsoft.com/Forums/vstudio/en-US/74a2dd29-7392-4936-b2ff-df149cc8547f/drag-amp-drop-files-from-32bit-winforms-application-to-64bit-outlook?forum=outlookdev

**Comment by landrix** [comment]
i think, it isn't possible

https://docs.microsoft.com/en-us/office/client-developer/outlook/mapi/building-mapi-applications-on-32-bit-and-64-bit-platforms#32-bit-mapi-application-and-64-bit-outlook
