### ISSUE TITLE
64 Bit Outlook and Demo app

### ISSUE THREAD

**Issue by markwilliams1234** [landrix/The-Drag-and-Drop-Component-Suite-for-Delphi#39]
I have just downloaded the latest version of Drag & Drop. Have used in the past with older versions of Delphi and 32-bit Outlook.

Now using Delphi 10.3 and trying to drag a message from 64-bit Outlook to the Outlook Demo App ("DemosWithoutInstall/Outlook") and it doesn't work. The forbidden icon never changes and dropping has no effect.

I've tried compiling the demo app in 32 and 64 bit and it makes no difference. 

I can drag and drop into explorer from Outlook without issue.

When I close the demo app, Outlook pops up a message 

> Either there is no default mail client or the current mail client cannot fulfill the messaging request. Please run Microsoft Outlook and set it as the default mail client.

I have had a browse online to see what is causing the above message and it looks like it might be a registry issue. I've tried various fixes recommended, but still get the issue (including full uninstall and reinstall of office).

Outlook appears to be correctly set as default mail app, but I wouldn't have thought that would be a problem anyway.

**Comment by landrix** [comment]
https://github.com/landrix/The-Drag-and-Drop-Component-Suite-for-Delphi/commit/468248311525761edd73eb34b60f14c7464008dd
