### ISSUE TITLE
Cannot recieve Droped files if the application is running as Administrator

### ISSUE THREAD

**Issue by YogiYang** [landrix/The-Drag-and-Drop-Component-Suite-for-Delphi#43]
Hello,

I am trying out the component suit. And while testing I found that it cannot receive Dropped files from Explorer if the application is run as Administrator.

How to solve this problem?

**Comment by landrix** [comment]
https://github.com/landrix/The-Drag-and-Drop-Component-Suite-for-Delphi/issues/17

**Comment by landrix** [comment]
it isn't posssible
lower privilege processes can’t interfere with higher privilege processes

https://stackoverflow.com/questions/17416765/drag-and-drop-event-can-not-be-fired-when-running-visual-studio-in-administrator

http://patrickablog.azurewebsites.net/index.php/2010/01/28/q-why-doesnt-drag-and-drop-work-when-my-application-is-running-elevated-a-mandatory-integrity-control-and-uipi/

**Comment by WIZZsWIZZs** [comment]
According to this post it can be done.
[https://stackoverflow.com/questions/57976627/delphi-drag-and-drop-files-from-windows-explorer-to-tlistview-does-not-work](url)
Therefor I was hoping it could be applied to the component as well.
