### ISSUE TITLE
TDropFileTarget: Abort notification?

### ISSUE THREAD

**Issue by PeterPanino** [landrix/The-Drag-and-Drop-Component-Suite-for-Delphi#60]
TDropFileTarget: This component works very well: Unfortunately, while dragging over the target, there is no event handler to be notified when the user ABORTS the Drag-Drop by e.g. pressing the ESC key.
Please add this event: **OnAbortDragDrop** or similar.

**Comment by andersmelander** [comment]
The drop target isn't notified about an abort because it's none of its business. The functionality you're asking for doesn't exist because it isn't possible to implement; The COM drag/drop framework doesn't provide the feedback you need so neither do the components.

**Comment by landrix** [comment]
@andersmelander Thanks for your additions.
