### ISSUE TITLE
Need help to generate C++Builder files

### ISSUE THREAD

**Issue by zurcuer** [landrix/The-Drag-and-Drop-Component-Suite-for-Delphi#66]
In order to use it with C++Builder 11, I changed the C/C++ Output file generation from 'Generate DCU Only' to 'Generate all C++ builder files'. I'm trying to generate the .lib file and am getting the following error:

DragDropPIDL.pas(1,1): error E1025: E1025 Unsupported language feature: 'import of DLL symbol by ordinal'

Even with the error, this creates the .lib file but it does not work due to unresolved '' external symbol in DragDropPIDL

I'm trying to build it with Delphi 11. We previously used an older version of this component for XE5 more than 8 years ago. I'm a bit lost on how to fix it.

Any idea how to do this? Thanks in advance

**Comment by landrix** [comment]
Sorry, I have no experience with C++. Can someone help?

**Comment by zurcuer** [comment]
I found the solution here:

http://www.devsuperpage.com/search/Articles.aspx?G=2&ArtID=5475

Basically I had to add "BCB" to the conditional defines to make it work
