### ISSUE TITLE
Errors installing in Delphi 12.1 and 11.3

### ISSUE THREAD

**Issue by DuckOfDevastation** [landrix/The-Drag-and-Drop-Component-Suite-for-Delphi#77]
Hi,

I am struggling with the installation under 12.1 and 11.3. 
After "Install" of the dclDragDropDRXX.bpl I get:

[dcc32 Fataler Fehler] DragDropDR11A.dpk(30): E2225 'Never-build' Package 'designide' muss neu compiliert werden
[dcc32 Fataler Fehler] dclDragDropDR11A.dpk(46): E2202 Package 'DragDropDR11A' wird benötigt, konnte aber nicht gefunden werden

I used dclDragDropDR11A.dpk for 11.3 and dclDragDropDR12.dpk for 12.1 - do they only work for 11.0 and 12.0? 

Thanks,

Sven

**Comment by landrix** [comment]
Do you have compiled DragDropDR11A.dpk

or DragDropDR12.dpk?

**Comment by DuckOfDevastation** [comment]
As you mention it, I possibly used dclDragDropDRXX.dpk instead of DragDropDRXX.dpk... but I'm not sure about that.
In the meantime I installed Delphi 12.0 and managed to install the drag and drop component suite without problems.

I'll reinstall Delphi 12.1 and check again, perhaps I'll just used the wrong .dpk. I'll post the results here.

Thx for your help,

Sven
